### PR TITLE
Adds gitguardian pre-commit hook

### PR DESCRIPTION
**Pull request by tnodell**
https://app.clickup.com/t/2704425/ID-5738

This installs a pre-commit step to prevent sensitive data from being committed.

Once this is merged, you will have to:

1. Install ggShield

`brew install gitguardian/tap/ggshield` 

2. Install pre-commit

`brew install pre-commit`

3. install dependencies
4. `pre-commit install` at the root of the project
5. `ggshield auth login` to Connect your Github account to GitGuardian. On your next commit, you will be asked to authenticate with GitGuardian. 

Now a precommit hook will run every time a commit is made.

https://docs.gitguardian.com/ggshield-docs/integrations/git-hooks/pre-commit

https://github.com/exogee-technology/graphweaver/assets/81122022/ee3c4527-3382-4285-9858-916f77d88bee

### CODE REVIEW

**Review by dylanlt — COMMENTED** [review]
I am unable to run "pnpm i" without errors, so I have only done the first steps. At this point I can still commit to my local branch.

**Comment by siowhoi** [comment]
Need to run `pre-commit install`

**Review by steve-keep — CHANGES_REQUESTED** [review]
I'm uncomfortable using GitGuardian here as anyone looking to contribute to the repo would need to connect their Github account to GitGuardian.

Instead, we should look to implement https://github.com/gitleaks/gitleaks as it is open-source and widely adopted.

**Comment by tnodell** [comment]
Closing in favor of 
https://github.com/exogee-technology/graphweaver/pull/202

**Pull request closed without merging**
